### ISSUE TITLE
future work that remains to be done

### ISSUE THREAD

**Issue by cfrick13** [aics-int/multiplex_immuno_processing#7]
need to add the following eventually (not necessarily within this branch):

- [x]  add try except line to allow some positions to fail alignment. and record in dataframe when alignment fails. 

- [x] add ability to save out processing into a testing folder (perhaps...call it `aligned_4i_exports_{testingname}`)
  - this is done using the `--test_save test` argument
  
- [ ] determine what crop size to use and adjust so that code doesn't take so long (we decided to use a crop to the time-lapse image so the final size will 1248x1848)

- don't save images using skimage [find a better package?]

- [x] develop jinja template to submit processing to slurm on a position by position basis. (for compute alignment parameters and for execute alignment)
- [x] need to revisit the question of how to save the alignned images and how to name them (be sure to check if they have unique filenames). Maybe you should write this as its own script and generate a dataframe with all the save names that will be generated. (See below)
- [ ] AND add ability to export "unaligned" images so that you can make contact sheets of what lack of alignment looks like easily. 
- [ ] also need to correct the positions that do not have extracted well_id information
- [x] "Should we hardcode the final shape here? I'm thinking these might be better if we make this a function of the image dimensions maybe?"
- [x] also need to add alignment of label-free to this workflow (And getting the camera aligned images)

### High level changes:
- [ ] make the config files static in one location
- [ ] config files should have their own git for version changes
- [ ] save outputs into one stable location (ad/comp/data?)

### BIGGEST CHANGES WE NEED:
- [ ] need to create a dataframe that documents the filepath and details of all split files
- [ ] make alignment faster by 1) pre-computing max projection (MIP) files. 
- [ ] make alignment faster by 2) computing alignment parameters only in X,Y on the MIPs. 3) 
- [ ] make alignment faster by 3) executing the alignment on the 2D images. 
- [ ] make a contact sheet that overlays round 00  (green) with a max projection of all other rounds (magenta; each intensity normalized)

### Other needed changes
- [ ] generate camera aligned images for all files
- [ ] find camera aligned ome tiff images in workflow and use those for processing steps. 

_Originally posted by @cfrick13 in https://github.com/aics-int/multiplex_immuno_processing/issues/5#issuecomment-1218539851_

**Comment by cfrick13** [comment]
- also need to correct the positions that do not have extracted `well_id` information

**Comment by cfrick13** [comment]
> Should we hardcode the final shape here? I'm thinking these might be better if we make this a function of the image dimensions maybe?

**Comment by cfrick13** [comment]
- also need to add alignment of label-free to this workflow (And getting the camera aligned images)

**Comment by cfrick13** [comment]
- make alignment faster by performing on 2D max projections. This will speed up computation of alignment parameters as well as speed up the execution of alignment
-

**Comment by cfrick13** [comment]
need to create a dataframe that documents the filepath and details of all split files

**Comment by gouthamr321** [comment]
Next steps to improve alignment:
- visualize features ORB for alignment
- visualize preprocessed images for correlation calculation
- Brainstorm improvements

**Comment by gouthamr321** [comment]
Improvements after merging feature_add_registration_branch that we discussed:

1. refactor execute_round_alignment.py and generate_alginment_parrameters.py to be able to run on [single position, all positions, or a list of positions](https://github.com/aics-int/multiplex_immuno_processing/pull/6/files/d6211aedbe125f14ad28bc74ffd26d665edb0046#diff-ba51fd1d81968f96751c4f17f74001256565c1b2c8e64d528688e68ecc1d8211))

2. Change the naming convention of column names in [generate_alignment_paramters.py](https://github.com/aics-int/multiplex_immuno_processing/pull/6/files/d6211aedbe125f14ad28bc74ffd26d665edb0046#diff-ebf02a45255fe76ac4ccdf0cf8fa9dfd40baaf8194dfb54769f19bf2ed40d354)

3. Save the alignment output file based on the type of method used for alignment in [generate_alignment_paramters.py](https://github.com/aics-int/multiplex_immuno_processing/pull/6/files/d6211aedbe125f14ad28bc74ffd26d665edb0046#diff-ebf02a45255fe76ac4ccdf0cf8fa9dfd40baaf8194dfb54769f19bf2ed40d354)

**Comment by gouthamr321** [comment]
We also need to have a jinja tempelate for aligning Benji's labelfree predictions independently per position

**Comment by gouthamr321** [comment]
When using slurm, It would be nice to have a script that tells you which positions haven't been run after a certain period of time. There is an issue where jobs are being queued, but they aren't actually being run on some nodes

**Comment by gouthamr321** [comment]
closing this since most of this is either already addressed or addressed in the snakemake PR.... will split out any remaining changes in different issues
