### ISSUE TITLE
Remove zero padding border from 4i immunostaining rounds

### ISSUE THREAD

**Issue by derekthirstrup** [aics-int/multiplex_immuno_processing#9]
Remove the zero padded pixel border from the 4i staining rounds to crop to the timelapse FOV image dimensions at the end of the image channel alignment script.

**Comment by cfrick13** [comment]
I am assigning myself to this issue :)

**Comment by cfrick13** [comment]
# to perform this processing, I followed what is written below:
First I wrote a new script to do this processing called `bandaid_crop_exported_images_to_timelapse_img.py`

### bandaid step: run to crop out the padding pixels
```
python ./multiplex_immuno_processing/bandaid_crop_exported_images_to_timelapse_img.py  --output_path "//allen/aics/assay-dev/users/Frick/PythonProjects/Assessment/4i_testing/aligned_4i_exports" --barcode 5500000724
```

### to run on slurm use
```
srun -p aics_cpu_general --mem 70G --pty bash #
module load anaconda3
source activate frick_multiplex_test
cd //allen/aics/assay-dev/users/Frick/PythonProjects/Assessment/4iProcessing-/
```

**Comment by cfrick13** [comment]
The old version of exported images looked like this
![5500000724-20x-P28-F8-](https://user-images.githubusercontent.com/22375032/187793699-339915de-7f16-4af9-b70e-b89c142d7a27.gif)

The new version (cropped to time-lapse) looks like this:
After
![5500000724-20x-P28-F8-](https://user-images.githubusercontent.com/22375032/187793819-243c23b7-a36d-4052-a8d6-5191d62e043e.gif)

**Comment by cfrick13** [comment]
I'm closing this issue. This is a bandaid-style fix though... Ideally we should decide not have a second script to crop our exports but instead we should decide on the crop we want and generate that directly in our `execute_round_alignment.py`. We will discuss more in our working group meetings


> Update: we are now removing the 0-value pixel borders from our ruond-aligned max intensity projection exports. This was found to make the images too large (Derek's processing steps took much longer) and caused some steps in Derek's code to break (detecting cell/nuclei at edges). To resolve this, I wrote a script that crops everything based on the time-lapse image. So the new output size is 1248x1848 (size of timelapse image) and the time-lapse image will not be cropped at all. The other rounds may be shifted out of the field of view relative to the time-lapse image and therefore will have black pixels on one or two sides. (see gifs below to summarize)
